version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - DB_NAME_TEST=${DB_NAME_TEST}
      - DB_USER_TEST=${DB_USER_TEST}
      - DB_PASSWORD_TEST=${DB_PASSWORD_TEST}
      - DB_HOST_TEST=database_test
      - DB_PORT_TEST=${DB_PORT_TEST}
    networks:
      - amazon

  database:
    image: postgres:13.15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - amazon
  database_test:
    image: postgres:13.15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
    ports:
      - 5434:5432
    volumes:
      - ./database_test:/var/lib/postgresql/data
    networks:
      - amazon

networks:
  amazon:
