# Generated by Django 5.0.7 on 2024-07-26 19:08

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryView',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'product_inventory_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=builtins.min)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'indexes': [models.Index(fields=['name'], name='products_name_6f9890_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 1000)), name='price_greater_than_zero'),
        ),
    ]
