# Generated by Django 5.0.7 on 2024-07-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'items_sale',
                'verbose_name_plural': 'items_sales',
                'db_table': 'items_sales',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'db_table': 'sales',
                'indexes': [models.Index(fields=['creation_date'], name='sales_creatio_ac736a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(check=models.Q(('total__gt', 0)), name='total_greater_than_zero'),
        ),
        migrations.AddField(
            model_name='items_sales',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales'),
        ),
        migrations.AddIndex(
            model_name='items_sales',
            index=models.Index(fields=['sale'], name='items_sales_sale_id_ab0e78_idx'),
        ),
        migrations.AddIndex(
            model_name='items_sales',
            index=models.Index(fields=['product_inventory'], name='items_sales_product_3947de_idx'),
        ),
        migrations.AddConstraint(
            model_name='items_sales',
            constraint=models.UniqueConstraint(fields=('product_inventory', 'sale'), name='unique_sale_product'),
        ),
        migrations.AddConstraint(
            model_name='items_sales',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='quantity_items_sales_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='items_sales',
            constraint=models.CheckConstraint(check=models.Q(('price_product__gt', 0)), name='price_product_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='items_sales',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gt', 0)), name='subtotal_greater_than_zero'),
        ),
    ]
